# Generated by Django 6.0.3 on 2026-03-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('enseignant', models.CharField(max_length=100)),
                ('date_publication', models.DateField()),
            ],
        ),
    ]
