# Generated by Django 6.0.2 on 2026-03-24 21:57

import cours.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cours',
            name='date_publication',
            field=models.DateField(validators=[cours.models.valider_date]),
        ),
    ]
